language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
env:
  global:
    - secure: feVR4SA77lPhxbvocfTSnAU06jVIXElhx9EC6m02GUk6ei9AEgZ7sck6L0NkcAeVAO0391m2/GxJHc88d/RQiPbwSVCoweMVPBnYS8mQPCPH2ZIfsdXokeUfRYJDg5/ADeQQU2S6WBYIzdStqcjkrNAkT2c7cXdBGjk52wTWdZs=
    - secure: W5DKQZSSU9ZQIU/2sHUHisfPe8TwZWRf13l7EOo/5ko9LjCQo3oC+NEopgJborSMIvClE25gW691K4jV0YTY93BpLTVqQ/U5yFIR2AV7jkPqCc7vhNTpKrJlrYec4V6EokUD5OSK1bvL+RkFYoImJghNuXXNZhNC6qFBPWF78JA=
